import os
import pandas as pd
import numpy as np

def load_and_preprocess_data(data_path):
    print("Loading market data...")
    # Read HistoricalData.csv or sp500.csv
    file_path = os.path.join(data_path, 'HistoricalData.csv')
    if not os.path.exists(file_path):
        file_path = os.path.join(data_path, 'sp500.csv')
        
    df = pd.read_csv(file_path)
    # Standardize column names
    df.columns = [c.strip().lower().replace(' ', '_') for c in df.columns]
    
    # Handle date parsing based on common column names
    date_col = 'date' if 'date' in df.columns else df.columns[0]
    df[date_col] = pd.to_datetime(df[date_col])
    df = df.sort_values(by=date_col).set_index(date_col)
    
    # Ensure close price is numeric (clean symbols like '$' if present)
    price_col = 'close/last' if 'close/last' in df.columns else ('close' if 'close' in df.columns else df.columns[1])
    df['close'] = df[price_col].astype(str).str.replace('$', '').astype(float)
    
    print("Computing technical features...")
    # 1. RSI (14 periods)
    delta = df['close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / loss
    df['rsi'] = 100 - (100 / (1 + rs))
    
    # 2. Bollinger Bands (20 periods)
    ma = df['close'].rolling(window=20).mean()
    std = df['close'].rolling(window=20).std()
    df['bollinger_upper'] = ma + (std * 2)
    df['bollinger_lower'] = ma - (std * 2)
    
    # 3. MACD (12, 26, 9)
    exp1 = df['close'].ewm(span=12, adjust=False).mean()
    exp2 = df['close'].ewm(span=26, adjust=False).mean()
    df['macd'] = exp1 - exp2
    
    # Target definition: sign(return(D+1, D+2))
    price_d1 = df['close'].shift(-1)
    price_d2 = df['close'].shift(-2)
    ret_d1_d2 = (price_d2 - price_d1) / price_d1
    df['target'] = np.sign(ret_d1_d2)
    
    # Drop rows with NaN values generated by rolling/shifting
    df = df.dropna()
    return df

if __name__ == "__main__":
    data_dir = "../data" if os.path.exists("../data") else "data"
    df = load_and_preprocess_data(data_dir)
    print("Features engineered successfully. Shape:", df.shape)